addpath('utils','utils/parallel_computation/','utils/options/','utils/imagingtools/',...
'svm_robust/','scatnet_light/','dimensionality_reduction/','cross_validation/','create_config_for_dataset/',...
'create_config_for_dataset/split_functions','svm_robust/libsvm-compact-0.1/matlab/');
addpath_scatnet

